# Generated by Django 5.0.1 on 2024-01-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_products_stock_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
